#ifndef ERRORS_H
#define ERRORS_H

enum ErrorCodes {
    READ_ERROR = 101,
    MEMORY_ALLOCATION_ERROR,

    BAD_LENGTH = 301,
    BAD_NUMBER_OF_VERTICES,
    BAD_NUMBER_OF_EDGES,
    BAD_NUMBER_OF_LINES,
    BAD_VERTEX,
    NO_SPANNING_TREE,
};

#endif
